### ISSUE TITLE
background of results looks weird, depending on survey questions

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/dodontprereg#17]
Steps to reproduce:
1. start app
2. click on "convince"
3. admire very blue style

I dont know why, but it seems to happen every time there is only one survey. May @LukasWallrich has an idea, because I haven't followed the logic of the chained surveys...

**Comment by LukasWallrich** [comment]
Odd - no idea why that happens. Shall we try to set a consistent `shinythemes` across everything and see if that fixes it?

**Comment by LukasWallrich** [comment]
Fixed this now by making this case behave more like the others - I don't quite get why it makes a difference to render a NULL UI element in the background, but apparently it does.
